import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

interface Msg { role: 'user' | 'assistant'; text: string; ts: string; }

@Component({
  selector: 'app-public-chat',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <!-- Launcher -->
    <button class="pc-fab" *ngIf="!open" (click)="toggle()" title="Ask about our courses">
      <span class="pc-fab-emoji">💬</span>
      <span class="pc-fab-txt">Ask about courses</span>
    </button>

    <!-- Panel -->
    <div class="pc-panel" *ngIf="open">
      <div class="pc-head">
        <img class="pc-ava" [src]="zoeImg" alt="Zoe" (error)="avaFallback($event)">
        <div class="pc-head-txt">
          <b>Zoe</b> <span class="pc-sub">(AI Admissions)</span><br>
          <small>Ask about our courses &amp; fees</small>
        </div>
        <button class="pc-x" (click)="toggle()">✕</button>
      </div>

      <!-- Intro form (before first message) -->
      <div class="pc-body" *ngIf="!started">
        <p class="pc-intro">👋 Hi! I'm <b>Zoe</b>. Tell me a little about you and I'll help with our
          <b>programs</b> and <b>fees</b> (domestic &amp; international).</p>
        <label>Your name</label>
        <input [(ngModel)]="name" placeholder="e.g. Alex Kim">
        <label>Email</label>
        <input [(ngModel)]="email" type="email" placeholder="you@email.com">
        <label>Mobile</label>
        <input [(ngModel)]="mobile" placeholder="e.g. 416-555-0100">
        <button class="pc-start" (click)="start()" [disabled]="!canStart() || busy">
          {{ busy ? 'Starting…' : 'Start chat' }}</button>
        <p class="pc-note" *ngIf="!canStart()">Enter your name and an email or mobile to begin.</p>
      </div>

      <!-- Chat -->
      <div class="pc-thread" *ngIf="started">
        <div *ngFor="let m of messages" class="pc-msg" [class.me]="m.role==='user'" [class.ai]="m.role==='assistant'">
          <div class="pc-role" *ngIf="m.role==='assistant'">Zoe (AI Agent)</div>
          <div class="pc-text" [innerHTML]="md(m.text)"></div>
          <div class="pc-ts">{{ m.ts }}</div>
        </div>
        <div class="pc-thinking" *ngIf="busy">
          <img class="pc-ava sm" [src]="zoeImg" alt="Zoe" (error)="avaFallback($event)">
          <span class="pc-pill">Zoe is thinking <span class="d"></span><span class="d"></span><span class="d"></span></span>
        </div>
      </div>

      <div class="pc-input" *ngIf="started">
        <input [(ngModel)]="msg" (keyup.enter)="send()" placeholder="Type a short message…" [disabled]="busy">
        <button (click)="send()" [disabled]="busy || !msg.trim()">➤</button>
      </div>
      <p class="pc-foot" *ngIf="started">Replies are generated by Zoe, an AI assistant.</p>
    </div>
  `,
  styles: [`
    .pc-fab { position:fixed; right:20px; bottom:20px; z-index:1000; display:flex; align-items:center; gap:8px;
      background:#2b6cb0; color:#fff; border:0; border-radius:999px; padding:12px 18px; font-weight:700;
      box-shadow:0 8px 24px rgba(43,108,176,.4); cursor:pointer; }
    .pc-fab:hover { background:#245a97; }
    .pc-fab-emoji { font-size:1.2rem; } @media (max-width:520px){ .pc-fab-txt { display:none; } }
    .pc-panel { position:fixed; right:20px; bottom:20px; z-index:1001; width:360px; max-width:calc(100vw - 32px);
      height:560px; max-height:calc(100vh - 40px); background:#fff; border-radius:16px; overflow:hidden;
      display:flex; flex-direction:column; box-shadow:0 20px 60px rgba(0,0,0,.28); }
    .pc-head { display:flex; align-items:center; gap:10px; background:#2b6cb0; color:#fff; padding:14px 16px; }
    .pc-ava { width:40px; height:40px; border-radius:50%; background:#fff; object-fit:cover;
      border:2px solid rgba(255,255,255,.7); flex:none; }
    .pc-ava.sm { width:28px; height:28px; border:1px solid #e2e8f0; }
    .pc-head-txt { flex:1; line-height:1.2; } .pc-sub { opacity:.8; font-size:.8rem; } .pc-head-txt small { opacity:.85; }
    .pc-x { background:transparent; color:#fff; border:0; font-size:1.1rem; cursor:pointer; }
    .pc-body { padding:16px; overflow-y:auto; }
    .pc-intro { color:#4a5568; font-size:.92rem; }
    .pc-body label { display:block; font-size:.8rem; font-weight:600; color:#4a5568; margin:10px 0 4px; }
    .pc-body input { width:100%; padding:10px 12px; border:1px solid #e2e8f0; border-radius:9px; }
    .pc-start { width:100%; margin-top:14px; background:#2b6cb0; color:#fff; border:0; border-radius:9px;
      padding:11px; font-weight:700; cursor:pointer; } .pc-start:disabled { opacity:.55; }
    .pc-note { color:#a0aec0; font-size:.78rem; margin-top:8px; }
    .pc-thread { flex:1; overflow-y:auto; padding:14px; background:#f8fafc; }
    .pc-msg { margin-bottom:10px; padding:9px 13px; border-radius:14px; max-width:88%; font-size:.92rem; }
    .pc-msg.me { background:#2b6cb0; color:#fff; margin-left:auto; border-bottom-right-radius:4px; }
    .pc-msg.ai { background:#fff; border:1px solid #edf2f7; border-bottom-left-radius:4px; }
    .pc-role { font-size:.72rem; color:#2b6cb0; font-weight:700; margin-bottom:2px; }
    .pc-ts { font-size:.68rem; opacity:.6; margin-top:3px; }
    .pc-text strong { font-weight:700; } .pc-text em { color:#2b6cb0; }
    .pc-thinking { display:flex; align-items:center; gap:8px; }
    .pc-pill { background:#eef6ff; color:#0e7490; font-weight:700; font-size:.85rem; border-radius:999px;
      padding:7px 14px; display:inline-flex; gap:4px; align-items:center; }
    .pc-pill .d { width:6px; height:6px; border-radius:50%; background:#0e7490; animation:pcp 1.2s infinite; }
    .pc-pill .d:nth-child(2){animation-delay:.2s;} .pc-pill .d:nth-child(3){animation-delay:.4s;}
    @keyframes pcp { 0%,100%{opacity:.25;transform:scale(.8);} 50%{opacity:1;transform:scale(1.1);} }
    .pc-input { display:flex; gap:8px; padding:10px 12px; border-top:1px solid #edf2f7; }
    .pc-input input { flex:1; padding:10px 12px; border:1px solid #e2e8f0; border-radius:12px; }
    .pc-input button { background:#2b6cb0; color:#fff; border:0; border-radius:12px; padding:0 16px; font-size:1.05rem; cursor:pointer; }
    .pc-foot { text-align:center; color:#a0aec0; font-size:.72rem; margin:0; padding:4px 0 8px; }
  `],
})
export class PublicChatComponent {
  open = false; started = false; busy = false;
  name = ''; email = ''; mobile = ''; leadId: number | null = null;
  msg = ''; messages: Msg[] = [];
  // Zoe's stock headshot (female), with an inline-SVG fallback if offline.
  zoeImg = 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=160&h=160&fit=crop&crop=faces&q=85';
  avaFallback(e: Event) {
    const img = e.target as HTMLImageElement; img.onerror = null;
    img.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(
      '<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#f6a5c0"/><stop offset="1" stop-color="#c44f84"/></linearGradient></defs><rect width="96" height="96" fill="url(#g)"/><text x="50%" y="55%" fill="#fff" font-family="sans-serif" font-size="44" font-weight="700" text-anchor="middle" dominant-baseline="middle">Z</text></svg>');
  }

  constructor(private http: HttpClient) {
    const s = localStorage.getItem('lead');
    if (s) { try { const l = JSON.parse(s); this.name = l.name || ''; this.email = l.email || ''; this.mobile = l.mobile || ''; this.leadId = l.lead_id || null; } catch { /* ignore */ } }
  }

  toggle() {
    this.open = !this.open;
    if (this.open && !this.started && this.leadId) this.start();   // returning visitor -> greet
  }
  canStart() { return !!this.name.trim() && (!!this.email.trim() || !!this.mobile.trim()); }
  private now() { return new Date().toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }); }
  private persist() { localStorage.setItem('lead', JSON.stringify({ name: this.name, email: this.email, mobile: this.mobile, lead_id: this.leadId })); }
  private scroll() { setTimeout(() => { const el = document.querySelector('.pc-thread'); if (el) el.scrollTop = el.scrollHeight; }, 50); }

  start() {
    if (!this.canStart() || this.busy) return;
    this.busy = true;
    this.post('__start__').subscribe({
      next: (r: any) => { this.busy = false; this.started = true; this.leadId = r.lead_id; this.persist();
        this.messages.push({ role: 'assistant', text: r.answer, ts: this.now() }); this.scroll(); },
      error: () => { this.busy = false; },
    });
  }
  send() {
    const t = this.msg.trim(); if (!t || this.busy) return;
    this.messages.push({ role: 'user', text: t, ts: this.now() }); this.msg = ''; this.busy = true; this.scroll();
    this.post(t).subscribe({
      next: (r: any) => { this.busy = false; this.leadId = r.lead_id; this.persist();
        this.messages.push({ role: 'assistant', text: r.answer, ts: this.now() }); this.scroll(); },
      error: () => { this.busy = false; this.messages.push({ role: 'assistant', text: 'Sorry, I could not respond right now — please try again.', ts: this.now() }); this.scroll(); },
    });
  }
  private post(message: string) {
    return this.http.post('/api/public/chat', { name: this.name, email: this.email, mobile: this.mobile, message, lead_id: this.leadId });
  }
  md(s: string) {
    return (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;')
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/(^|[^*])\*([^*]+)\*/g, '$1<em>$2</em>')
      .replace(/\n/g, '<br>');
  }
}
